name: threego
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

awesome_snackbar_content: ^0.1.2
dependencies:
  auto_route: ^6.4.0
  barcode_widget: ^2.0.3
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.19
  google_nav_bar: ^5.0.6
  image_cropper: 3.0.3
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  kartal: ^2.8.0
  loading_animation_widget: ^1.2.0+4
  multi_select_flutter: ^4.1.3
  readmore: ^2.2.0
  share_plus: ^6.3.1
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  syncfusion_flutter_datepicker: ^21.1.37
  vexana: ^3.4.1

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mapStyle/dark_map.txt
    - assets/mapStyle/light_map.txt
    - assets/markers/ART.png
    - assets/markers/BUSINESS.png
    - assets/markers/CHARITABLE.png
    - assets/markers/COMMUNITY.png
    - assets/markers/COMPETITION.png
    - assets/markers/CULTURAL.png
    - assets/markers/EDUCATION.png
    - assets/markers/FOOD.png
    - assets/markers/MUSIC.png
    - assets/markers/RELIGIOUS.png
    - assets/markers/SHOOP.png
    - assets/markers/TOURISTY.png
    - assets/markers/test.png
    - assets/logo.png

flutter_native_splash:
  color: "#0F0F0F"
  image: assets/splashImage.gif
  android: true
  ios: true
analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  rules:
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - prefer-match-file-name
