name: threego
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  barcode: ^2.2.3
  barcode_widget: ^2.0.3
  bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.7
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  loading_animation_widget: ^1.2.0+4
  readmore: ^2.2.0
  ticket_widget: ^0.0.1
  uuid: ^3.0.7
  vexana: ^3.4.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/markers/ART.png
    - assets/markers/BUSINESS.png
    - assets/markers/CHARITABLE.png
    - assets/markers/COMMUNITY.png
    - assets/markers/COMPETITION.png
    - assets/markers/CULTURAL.png
    - assets/markers/EDUCATION.png
    - assets/markers/FOOD.png
    - assets/markers/MUSIC.png
    - assets/markers/RELIGIOUS.png
    - assets/markers/SHOOP.png
    - assets/markers/TOURISTY.png
    - assets/markers/test.png
    - assets/logo.png

flutter_native_splash:
  color: "#0F0F0F"
  image: assets/splashImage.gif
  android: true
  ios: true
